# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20180210_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'BitCoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin')], max_length=3)),
                ('last_tracked_price', models.FloatField()),
                ('recorded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_on_rate', models.FloatField(default=0)),
                ('notification_criteria', models.CharField(choices=[('UP', 'Up'), ('DN', 'Down')], max_length=2)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
